-- MySQL Script generated by MySQL Workbench
-- Wed Aug 21 20:18:52 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema requerimiento
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema requerimiento
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `requerimiento` DEFAULT CHARACTER SET latin1 ;
USE `requerimiento` ;

-- -----------------------------------------------------
-- Table `requerimiento`.`asignado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `requerimiento`.`asignado` (
  `id` INT(11) NOT NULL,
  `asignado` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `requerimiento`.`gerencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `requerimiento`.`gerencia` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nomgerencia` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `requerimiento`.`detop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `requerimiento`.`detop` (
  `iddetop` INT(11) NOT NULL,
  `idgerencia` INT(11) NOT NULL,
  `departamento` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`iddetop`),
  INDEX `idgerencia_idx` (`idgerencia` ASC),
  CONSTRAINT `idgerencia`
    FOREIGN KEY (`idgerencia`)
    REFERENCES `requerimiento`.`gerencia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `requerimiento`.`encargado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `requerimiento`.`encargado` (
  `idencargado` INT(11) NOT NULL,
  `idasignado` INT(11) NOT NULL,
  `nomencargado` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`idencargado`),
  INDEX `idasignado_idx` (`idasignado` ASC),
  CONSTRAINT `idasignado`
    FOREIGN KEY (`idasignado`)
    REFERENCES `requerimiento`.`asignado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `requerimiento`.`ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `requerimiento`.`ingreso` (
  `idingreso` INT(11) NOT NULL AUTO_INCREMENT,
  `gerencia` INT NOT NULL,
  `depto` INT NOT NULL,
  `asignar` INT NOT NULL,
  `encargado` INT NOT NULL,
  `req` INT NOT NULL,
  `estado` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`idingreso`),
  INDEX `encargado_idx` (`encargado` ASC),
  INDEX `gerencia_idx` (`gerencia` ASC),
  INDEX `asingar_idx` (`asignar` ASC),
  INDEX `detop_idx` (`depto` ASC),
  CONSTRAINT `encargado`
    FOREIGN KEY (`encargado`)
    REFERENCES `requerimiento`.`encargado` (`idencargado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `gerencia`
    FOREIGN KEY (`gerencia`)
    REFERENCES `requerimiento`.`gerencia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `asingar`
    FOREIGN KEY (`asignar`)
    REFERENCES `requerimiento`.`asignado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `detop`
    FOREIGN KEY (`depto`)
    REFERENCES `requerimiento`.`detop` (`iddetop`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `requerimiento`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `requerimiento`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(70) NOT NULL,
  `Email` VARCHAR(70) NOT NULL,
  `Password` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
